version: "3.9"

services:
  shogihome:
    image: shogihome:latest
    container_name: shogihome
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      HOST: 0.0.0.0
    restart: unless-stopped

